export const verses = [
 "John 3:16",
 "Psalm 23:1",
 "Romans 8:28",
 "Philippians 4:13",
 "Proverbs 3:5",
 "Isaiah 41:10",
 "Matthew 6:33",
 "Jeremiah 29:11",
 "Hebrews 11:1",
 "2 Timothy 1:7",
 "1 Peter 5:7",
 "Joshua 1:9",
 "Romans 12:2",
 "Psalm 46:1",
 "James 1:5",
 "1 Corinthians 10:13",
 "John 14:6",
 "Psalm 91:1",
 "Ephesians 2:8",
 "Galatians 5:22",
 "Colossians 3:23",
 "Matthew 11:28",
 "1 John 4:18",
 "Isaiah 40:31",
 "Luke 1:37",
 "Romans 5:8",
 "Proverbs 18:10",
 "2 Corinthians 5:17",
 "Psalm 119:105",
 "Matthew 5:14"
];

export const passages = [
 "For God so loved the world that he gave his one and only Son...",
 "The Lord is my shepherd; I shall not want.",
 "And we know that in all things God works for the good of those who love him...",
 "I can do all things through Christ who strengthens me.",
 "Trust in the Lord with all your heart and lean not on your own understanding.",
 "Fear not, for I am with you; be not dismayed, for I am your God...",
 "But seek first his kingdom and his righteousness...",
 "For I know the plans I have for you, declares the Lord...",
 "Now faith is confidence in what we hope for and assurance about what we do not see.",
 "For God gave us a spirit not of fear but of power and love and self-control.",
 "Cast all your anxiety on him because he cares for you.",
 "Have I not commanded you? Be strong and courageous. Do not be frightened...",
 "Do not conform to the pattern of this world, but be transformed by the renewing of your mind...",
 "God is our refuge and strength, an ever-present help in trouble.",
 "If any of you lacks wisdom, let him ask of God...",
 "No temptation has overtaken you except what is common to mankind...",
 "Jesus answered, 'I am the way and the truth and the life...'",
 "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.",
 "For it is by grace you have been saved, through faith...",
 "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness...",
 "Whatever you do, work at it with all your heart, as working for the Lord...",
 "Come to me, all who are weary and burdened, and I will give you rest.",
 "There is no fear in love. But perfect love drives out fear...",
 "But those who hope in the Lord will renew their strength...",
 "For nothing will be impossible with God.",
 "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
 "The name of the Lord is a fortified tower; the righteous run to it and are safe.",
 "Therefore, if anyone is in Christ, the new creation has come...",
 "Your word is a lamp for my feet, a light on my path.",
 "You are the light of the world. A town built on a hill cannot be hidden."
];